spring.application.name=spring_boot_mysql
spring.datasource.url=jdbc:mysql://localhost:3306/suresh
spring.datasource.username=root
spring.datasource.password=suree
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8081
