spring.datasource.url=jdbc:sqlserver://suree.database.windows.net:1433;database=suresh;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=suresh@suree
spring.datasource.password=Suree79@75
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect